version: "2"
services:
    api:
        build:
            dockerfile: ./Dockerfile
            context: .
        volumes: 
            - .:/app
        ports:
            - 3000:3000
        depends_on: 
            - dbsol
        # environment: 
        #     NODE_ENV: production
    dbsol:
        image: postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        # restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: edjfdhasm234
            POSTGRES_USER: lrge
            POSTGRES_DB: sdc_api_development