version: "2"
services:
    web:
        build:
            dockerfile: ./Dockerfile
            context: .
        volumes: 
            - .:/app
        ports:
            - 3000:3000
        depends_on: 
            - db
        # environment: 
        #     NODE_ENV: production
    db:
        image: postgres
        volumes:
            - ./tmp/db/:/var/lib/postgresql/data
        # restart: always
        environment:
            POSTGRES_PASSWORD: edjfdhasm234
            POSTGRES_USER: lrge