version: "2"
services:
    web:
        build:
            dockerfile: ./Dockerfile
            context: .
        volumes: 
            - .:/app
        ports:
            - 3000:3000
        depends_on: 
            - db
    db:
        image: postgres
        # restart: always
        environment:
            POSTGRES_PASSWORD: edjfdhasm234
            POSTGRES_USER: lrge