version: "2"
services:
    api:
        image: thhegal/sol-cloud-api:latest
        ports:
            - 3000:3000

    nginx:
        image: nginx
        volumes:
            - ./distAdmin:/usr/share/nginx/html/admin
            - ./distCoop:/usr/share/nginx/html/coop
            - ./distSupplier:/usr/share/nginx/html/supplier
            - ./nginx_admin.conf:/etc/nginx/conf.d/default.conf
            - ./nginx_coop.conf:/etc/nginx/conf.d/coop.conf
            - ./nginx_supplier.conf:/etc/nginx/conf.d/supplier.conf
        ports:
            - 8083:80
        depends_on:
            - adminBuild
            - coopBuild
            - supplierBuild
        # environment:
            # - NGINX_HOST=foobar.com
            # - NGINX_PORT=80

    adminBuild:
        image: thhegal/sol-cloud-admin:latest
        volumes:
            - ./secrets_admin.yml:/app/src/config/secrets.yml
            - ./distAdmin:/app/build

    coopBuild:
        image: thhegal/sol-cloud-cooperative:latest
        volumes:
            - ./secrets_coop.yml:/app/src/config/secrets.yml
            - ./distCoop:/app/build

    supplierBuild:
        image: thhegal/sol-cloud-supplier:latest
        volumes:
            - ./secrets_supp.yml:/app/src/config/secrets.yml
            - ./distSupplier:/app/build